apiVersion: v1
kind: ConfigMap
metadata: 
  name: node-api-config
  namespace: node-api-app
data: 
  NODE_ENV: "production"
  PORT: "3000"
  MONGO_URL: "mongodb://mongo-0.mongo:27017/mydb"


  # A configMap stores configuration values like:
  #*URL'S ,environmental variable , feature flags,database hostname,app-level settings ,json/yaml configs
   #so your pod can load these values at the runtime
