apiVersion: v1
kind: Service
metadata: 
  name: node-api-service
  namespace: node-api-app
spec: 
  selector:
    app: node-api
  ports: 
  - port: 80                            #service port
    targetPort: 3000                    #pod port 
  type: ClusterIP
