apiVerison: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:  
  name: myapp-hpa
spec: 
  scaleTragetRef: 
    apiVersion: app/v1
    kind: Deployment
    name: python-app
  minReplicas: 2
  maxReplicas: 10
  metixs: 
    - type: Resources
      resource:
        name: cpu
        target: 
          type: utilization
          averageUtilization: 60
